[2024-04-24T06:34:07.569+0000] {processor.py:161} INFO - Started process (PID=715) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:34:07.570+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:34:07.571+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:34:07.571+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:34:07.580+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:34:07.578+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:34:07.581+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:34:07.595+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.028 seconds
[2024-04-24T06:34:37.707+0000] {processor.py:161} INFO - Started process (PID=723) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:34:37.707+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:34:37.709+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:34:37.708+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:34:37.714+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:34:37.713+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:34:37.715+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:34:37.725+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.020 seconds
[2024-04-24T06:35:07.866+0000] {processor.py:161} INFO - Started process (PID=731) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:35:07.867+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:35:07.868+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:35:07.867+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:35:07.873+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:35:07.872+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:35:07.873+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:35:07.884+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.020 seconds
[2024-04-24T06:35:38.007+0000] {processor.py:161} INFO - Started process (PID=739) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:35:38.007+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:35:38.009+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:35:38.008+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:35:38.014+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:35:38.013+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:35:38.015+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:35:38.026+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.021 seconds
[2024-04-24T06:36:08.173+0000] {processor.py:161} INFO - Started process (PID=747) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:36:08.174+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:36:08.175+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:36:08.175+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:36:08.181+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:36:08.180+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:36:08.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:36:08.192+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.021 seconds
[2024-04-24T06:36:38.342+0000] {processor.py:161} INFO - Started process (PID=755) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:36:38.342+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:36:38.343+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:36:38.343+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:36:38.349+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:36:38.348+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:36:38.349+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:36:38.361+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.022 seconds
[2024-04-24T06:37:08.481+0000] {processor.py:161} INFO - Started process (PID=763) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:37:08.482+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:37:08.483+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:37:08.483+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:37:08.488+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:37:08.487+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:37:08.489+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:37:08.500+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.020 seconds
[2024-04-24T06:37:38.621+0000] {processor.py:161} INFO - Started process (PID=771) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:37:38.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:37:38.623+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:37:38.623+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:37:38.630+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:37:38.628+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:37:38.630+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:37:38.641+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.022 seconds
[2024-04-24T06:38:08.757+0000] {processor.py:161} INFO - Started process (PID=779) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:38:08.757+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:38:08.759+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:38:08.758+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:38:08.765+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:38:08.764+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:38:08.766+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:38:08.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.022 seconds
[2024-04-24T06:38:38.890+0000] {processor.py:161} INFO - Started process (PID=787) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:38:38.891+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:38:38.893+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:38:38.893+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:38:38.898+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:38:38.897+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:38:38.899+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:38:38.911+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.022 seconds
[2024-04-24T06:39:09.038+0000] {processor.py:161} INFO - Started process (PID=795) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:39:09.038+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:39:09.039+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:39:09.039+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:39:09.045+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:39:09.044+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:39:09.045+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:39:09.056+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.021 seconds
[2024-04-24T06:39:39.189+0000] {processor.py:161} INFO - Started process (PID=803) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:39:39.190+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:39:39.191+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:39:39.191+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:39:39.197+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:39:39.195+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:39:39.197+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:39:39.208+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.020 seconds
[2024-04-24T06:40:09.348+0000] {processor.py:161} INFO - Started process (PID=811) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:40:09.349+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:40:09.351+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:40:09.351+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:40:09.358+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:40:09.357+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:40:09.359+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:40:09.380+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.035 seconds
[2024-04-24T06:40:39.530+0000] {processor.py:161} INFO - Started process (PID=819) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:40:39.531+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:40:39.532+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:40:39.531+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:40:39.537+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:40:39.536+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:40:39.537+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:40:39.555+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.027 seconds
[2024-04-24T06:41:09.703+0000] {processor.py:161} INFO - Started process (PID=827) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:41:09.703+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:41:09.704+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:41:09.704+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:41:09.710+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:41:09.708+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:41:09.710+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:41:09.722+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.021 seconds
[2024-04-24T06:41:39.871+0000] {processor.py:161} INFO - Started process (PID=835) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:41:39.871+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:41:39.873+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:41:39.872+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:41:39.878+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:41:39.877+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:41:39.878+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:41:39.890+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.022 seconds
[2024-04-24T06:42:10.022+0000] {processor.py:161} INFO - Started process (PID=843) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:42:10.023+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:42:10.024+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:42:10.024+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:42:10.032+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:42:10.031+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:42:10.033+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:42:10.046+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.025 seconds
[2024-04-24T06:42:40.176+0000] {processor.py:161} INFO - Started process (PID=851) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:42:40.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:42:40.178+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:42:40.178+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:42:40.184+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:42:40.183+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:42:40.185+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:42:40.195+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.020 seconds
[2024-04-24T06:43:10.322+0000] {processor.py:161} INFO - Started process (PID=859) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:43:10.323+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:43:10.325+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:43:10.324+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:43:10.333+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:43:10.332+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:43:10.334+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:43:10.345+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.025 seconds
[2024-04-24T06:43:40.493+0000] {processor.py:161} INFO - Started process (PID=867) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:43:40.493+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:43:40.495+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:43:40.494+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:43:40.501+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:43:40.500+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:43:40.501+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:43:40.521+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.030 seconds
[2024-04-24T06:44:10.692+0000] {processor.py:161} INFO - Started process (PID=875) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:44:10.693+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:44:10.694+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:44:10.694+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:44:10.700+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:44:10.699+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:44:10.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:44:10.711+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.020 seconds
[2024-04-24T06:44:40.822+0000] {processor.py:161} INFO - Started process (PID=883) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:44:40.823+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:44:40.824+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:44:40.824+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:44:40.829+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:44:40.828+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:44:40.830+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:44:40.856+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.035 seconds
[2024-04-24T06:45:10.983+0000] {processor.py:161} INFO - Started process (PID=891) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:45:10.984+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:45:10.985+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:45:10.985+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:45:10.990+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:45:10.989+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:45:10.991+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:45:11.008+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.027 seconds
[2024-04-24T06:45:41.144+0000] {processor.py:161} INFO - Started process (PID=899) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:45:41.145+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:45:41.146+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:45:41.146+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:45:41.152+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:45:41.150+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:45:41.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:45:41.170+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.028 seconds
[2024-04-24T06:46:11.302+0000] {processor.py:161} INFO - Started process (PID=907) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:46:11.303+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:46:11.304+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:46:11.304+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:46:11.309+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:46:11.308+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:46:11.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:46:11.320+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.020 seconds
[2024-04-24T06:46:41.437+0000] {processor.py:161} INFO - Started process (PID=915) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:46:41.438+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:46:41.440+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:46:41.439+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:46:41.446+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:46:41.444+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:46:41.446+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:46:41.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.029 seconds
[2024-04-24T06:47:11.617+0000] {processor.py:161} INFO - Started process (PID=923) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:47:11.618+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:47:11.619+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:47:11.619+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:47:11.624+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:47:11.623+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:47:11.625+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:47:11.639+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.024 seconds
[2024-04-24T06:47:41.761+0000] {processor.py:161} INFO - Started process (PID=931) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:47:41.762+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:47:41.763+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:47:41.763+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:47:41.770+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:47:41.768+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:47:41.771+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:47:41.783+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.023 seconds
[2024-04-24T06:48:11.931+0000] {processor.py:161} INFO - Started process (PID=939) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:48:11.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:48:11.933+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:48:11.933+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:48:11.938+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:48:11.937+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:48:11.939+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:48:11.950+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.021 seconds
[2024-04-24T06:48:42.079+0000] {processor.py:161} INFO - Started process (PID=947) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:48:42.080+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:48:42.081+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:48:42.081+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:48:42.088+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:48:42.086+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:48:42.089+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:48:42.102+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.025 seconds
[2024-04-24T06:49:12.253+0000] {processor.py:161} INFO - Started process (PID=955) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:49:12.254+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:49:12.255+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:49:12.254+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:49:12.261+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:49:12.259+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:49:12.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:49:12.272+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.021 seconds
[2024-04-24T06:49:42.394+0000] {processor.py:161} INFO - Started process (PID=963) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:49:42.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:49:42.396+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:49:42.396+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:49:42.402+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:49:42.401+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:49:42.402+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:49:42.413+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.021 seconds
[2024-04-24T06:50:12.555+0000] {processor.py:161} INFO - Started process (PID=971) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:50:12.555+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:50:12.557+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:50:12.557+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:50:12.563+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:50:12.561+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:50:12.563+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:50:12.574+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.022 seconds
[2024-04-24T06:50:42.689+0000] {processor.py:161} INFO - Started process (PID=979) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:50:42.690+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:50:42.691+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:50:42.691+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:50:42.696+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:50:42.695+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:50:42.696+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:50:42.715+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.028 seconds
[2024-04-24T06:51:12.864+0000] {processor.py:161} INFO - Started process (PID=987) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:51:12.865+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:51:12.866+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:51:12.866+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:51:12.873+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:51:12.871+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:51:12.874+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:51:12.887+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.025 seconds
[2024-04-24T06:51:43.008+0000] {processor.py:161} INFO - Started process (PID=995) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:51:43.009+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:51:43.010+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:51:43.010+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:51:43.016+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:51:43.015+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:51:43.016+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:51:43.035+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.029 seconds
[2024-04-24T06:52:13.178+0000] {processor.py:161} INFO - Started process (PID=1003) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:52:13.179+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:52:13.180+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:52:13.180+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:52:13.185+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:52:13.184+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:52:13.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:52:13.197+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.021 seconds
[2024-04-24T06:52:43.314+0000] {processor.py:161} INFO - Started process (PID=1011) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:52:43.315+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:52:43.316+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:52:43.315+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:52:43.322+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:52:43.321+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:52:43.322+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:52:43.333+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.021 seconds
[2024-04-24T06:53:13.447+0000] {processor.py:161} INFO - Started process (PID=1019) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:53:13.448+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:53:13.449+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:53:13.449+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:53:13.455+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:53:13.454+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:53:13.456+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:53:13.467+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.022 seconds
[2024-04-24T06:53:43.593+0000] {processor.py:161} INFO - Started process (PID=1027) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:53:43.593+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:53:43.594+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:53:43.594+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:53:43.600+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:53:43.599+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:53:43.601+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:53:43.613+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.023 seconds
[2024-04-24T06:54:13.741+0000] {processor.py:161} INFO - Started process (PID=1035) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:54:13.741+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:54:13.743+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:54:13.743+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:54:13.750+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:54:13.749+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:54:13.750+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:54:13.761+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.022 seconds
[2024-04-24T06:54:43.889+0000] {processor.py:161} INFO - Started process (PID=1043) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:54:43.890+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:54:43.891+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:54:43.891+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:54:43.896+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:54:43.895+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:54:43.897+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:54:43.910+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.023 seconds
[2024-04-24T06:55:14.033+0000] {processor.py:161} INFO - Started process (PID=1051) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:55:14.034+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:55:14.035+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:55:14.035+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:55:14.041+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:55:14.040+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:55:14.041+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:55:14.053+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.021 seconds
[2024-04-24T06:55:44.191+0000] {processor.py:161} INFO - Started process (PID=1059) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:55:44.192+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:55:44.193+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:55:44.193+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:55:44.198+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:55:44.197+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:55:44.199+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:55:44.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.022 seconds
[2024-04-24T06:56:14.337+0000] {processor.py:161} INFO - Started process (PID=1067) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:56:14.337+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:56:14.338+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:56:14.338+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:56:14.344+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:56:14.343+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:56:14.345+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:56:14.359+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.025 seconds
[2024-04-24T06:56:44.504+0000] {processor.py:161} INFO - Started process (PID=1075) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:56:44.504+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:56:44.505+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:56:44.505+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:56:44.511+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:56:44.509+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:56:44.511+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:56:44.522+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.021 seconds
[2024-04-24T06:57:14.642+0000] {processor.py:161} INFO - Started process (PID=1082) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:57:14.643+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:57:14.644+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:57:14.644+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:57:14.649+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:57:14.648+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:57:14.650+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:57:14.662+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.021 seconds
[2024-04-24T06:57:44.792+0000] {processor.py:161} INFO - Started process (PID=1090) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:57:44.794+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:57:44.795+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:57:44.795+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:57:44.808+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:57:44.806+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:57:44.809+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:57:44.822+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.032 seconds
[2024-04-24T06:58:14.944+0000] {processor.py:161} INFO - Started process (PID=1098) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:58:14.945+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:58:14.946+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:58:14.946+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:58:14.952+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:58:14.951+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag.py", line 9, in <module>
    default_args = {'owner': airflow,
NameError: name 'airflow' is not defined
[2024-04-24T06:58:14.953+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:58:14.966+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.024 seconds
[2024-04-24T06:58:18.994+0000] {processor.py:161} INFO - Started process (PID=1099) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:58:18.994+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:58:18.996+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:58:18.996+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:58:19.008+0000] {processor.py:840} INFO - DAG(s) 'checking_vscode' retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:58:19.064+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:58:19.064+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:checking_vscode
[2024-04-24T06:58:19.070+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:58:19.069+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:checking_vscode
[2024-04-24T06:58:19.073+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:58:19.073+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:checking_vscode
[2024-04-24T06:58:19.074+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:58:19.073+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-24T06:58:19.080+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:58:19.080+0000] {dag.py:3069} INFO - Creating ORM DAG for checking_vscode
[2024-04-24T06:58:19.086+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:58:19.086+0000] {dag.py:3834} INFO - Setting next_dagrun for checking_vscode to 2024-04-25 00:00:00+00:00, run_after=2024-04-26 00:00:00+00:00
[2024-04-24T06:58:19.096+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.104 seconds
[2024-04-24T06:58:49.135+0000] {processor.py:161} INFO - Started process (PID=1107) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:58:49.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:58:49.137+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:58:49.136+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:58:49.147+0000] {processor.py:840} INFO - DAG(s) 'checking_vscode' retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:58:49.163+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:58:49.162+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-24T06:58:49.176+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:58:49.176+0000] {dag.py:3834} INFO - Setting next_dagrun for checking_vscode to 2024-04-25 00:00:00+00:00, run_after=2024-04-26 00:00:00+00:00
[2024-04-24T06:58:49.187+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.054 seconds
[2024-04-24T06:59:19.336+0000] {processor.py:161} INFO - Started process (PID=1115) to work on /opt/airflow/dags/second_dag.py
[2024-04-24T06:59:19.336+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/second_dag.py for tasks to queue
[2024-04-24T06:59:19.337+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:59:19.337+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag.py
[2024-04-24T06:59:19.346+0000] {processor.py:840} INFO - DAG(s) 'checking_vscode' retrieved from /opt/airflow/dags/second_dag.py
[2024-04-24T06:59:19.361+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:59:19.361+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-24T06:59:19.373+0000] {logging_mixin.py:188} INFO - [2024-04-24T06:59:19.373+0000] {dag.py:3834} INFO - Setting next_dagrun for checking_vscode to 2024-04-25 00:00:00+00:00, run_after=2024-04-26 00:00:00+00:00
[2024-04-24T06:59:19.384+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/second_dag.py took 0.050 seconds
